# in _config.yml
title: "Yuan's notes"
author: ""
# logo: src/public/icon.png
execute:
  execute_notebooks: "off"
copyright: "2021-2023 by Yuan Zhang"
only_build_toc_files: true

html:
  favicon: "src/public/icon.png"
  use_repository_button: true
  baseurl: "https://mtngtnsh.github.io/jb-notes/"

repository:
  url: "https://github.com/mtngtnsh/jb-notes/"
  branch: main