---
name: automerge

on:
  pull_request:
    branches:
      - release-please--branches--main--components--jb-notes
  schedule:
    - cron: "15 4 * * 4"

env:
  GITHUB_USERNAME: "motoish"
  MASTER_BRANCH: main

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  id-token: write
  issues: write
  discussions: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: read
  security-events: read
  statuses: read

jobs:
  merge:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Check if pr exists
        id: check-pr
        run: |
          echo "count=$(gh pr list -s open -B "$MASTER_BRANCH" | wc -l)" >> "$GITHUB_OUTPUT"

      - name: Merge Pull Requests
        if: ${{ steps.check-pr.outputs.count > 0 }}
        run: |
          gh pr checkout "$MASTER_BRANCH"
          gh pr merge --admin
