---
name: Release

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed

permissions:
  contents: write
  pull-requests: write

jobs:
  linter:
    name: Linter
    if: ${{ github.event.pull_request.merged == false }}
    uses: ./.github/workflows/mega-linter.yml

  release-please:
    if: ${{ github.event.pull_request.merged == false }}
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          package-name: jb-notes
