---
name: Release

on:
  push:
    branches:
      - main

permissions:
  actions: read
  checks: read
  contents: write
  deployments: read
  id-token: write
  issues: read
  discussions: read
  packages: read
  pages: read
  pull-requests: write
  repository-projects: read
  security-events: read
  statuses: read

jobs:
  getenv:
    name: Env
    runs-on: ubuntu-latest
    outputs:
      head_commit: ${{ steps.setenv.outputs.head_commit }}
    steps:
      - uses: actions/checkout@v3

      - name: Echo env
        id: setenv
        env:
          MESSAGE: ${{ github.event.head_commit.message }}
        run: |
          echo "github.event.head_commit.message: ${{ env.MESSAGE }}"
          echo "head_commit=${{ env.MESSAGE }}" | sed ':a;N;$!ba;s/\n//g' | awk '{print $1}' >> "$GITHUB_OUTPUT"

  linter:
    name: Linter
    needs: [getenv]
    if: ${{ !contains(needs.getenv.outputs.head_commit, 'Merge') }}
    uses: ./.github/workflows/mega-linter.yml

  release-please:
    name: Release-PR
    runs-on: ubuntu-latest
    needs: [getenv, linter]
    if: ${{ !contains(needs.getenv.outputs.head_commit, 'Merge') }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          package-name: jb-notes
