---
name: Release

on:
  push:
    branches:
      - main

permissions:
  actions: read
  checks: read
  contents: write
  deployments: read
  id-token: write
  issues: read
  discussions: read
  packages: read
  pages: read
  pull-requests: write
  repository-projects: read
  security-events: read
  statuses: read

jobs:
  env:
    name: Env
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Echo env
        run: |
          echo 'github.base_ref: ${{ github.base_ref }}'
          echo 'github.ref: ${{ github.ref }}'
          echo 'github.ref_name: ${{ github.ref_name }}'
          echo 'github.event_name: ${{ github.event_name }}'
          echo 'github.event: ${{ github.event.ref }}'
          echo 'github.action_ref: ${{ github.action_ref }}'
          echo 'github.event_path:${{ github.event_path }}'
          echo 'github.event.commits.message: ${{ github.event.commits.message }}'
          echo 'github.event.head_commit.message: ${{ github.event.head_commit.message }}'
          echo 'github.action_ref: ${{github.action_ref }}'
          echo 'github.env: ${{ github.env }}'
          echo 'github.event.sender: ${{ github.event.sender }}'

  linter:
    name: Linter
    if: ${{ github.event_name == 'push' && github.head_ref == null }}
    uses: ./.github/workflows/mega-linter.yml

  release-please:
    name: Release
    if: ${{ github.event_name == 'push' && github.head_ref == null }}
    runs-on: ubuntu-latest
    needs: linter
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          package-name: jb-notes
