---
name: Release

on:
  push:
    branches:
      - main

permissions:
  actions: read
  checks: read
  contents: write
  deployments: read
  id-token: write
  issues: read
  discussions: read
  packages: read
  pages: read
  pull-requests: write
  repository-projects: read
  security-events: read
  statuses: read

jobs:
  linter:
    name: Linter
    if: ${{ github.event_name }} == "push" && ${{ github.ref }} == "refs/heads/main"
    uses: ./.github/workflows/mega-linter.yml

  release-please:
    name: Release
    if: ${{ github.event_name }} == "push" && ${{ github.ref }} == "refs/heads/main"
    runs-on: ubuntu-latest
    needs: linter
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          package-name: jb-notes
