---
name: motoish.com

on:
  pull_request:
    types:
      - closed
    branches:
      - main

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  id-token: write
  issues: write
  discussions: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: read
  security-events: read
  statuses: read

jobs:
  deploy:
    name: Deploy
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: "**/requirements.txt"
      - run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Jupyter Book
        run: |
          cd ../
          jb build --all jb-notes
          cd -

      - name: Publish GitHub Pages
        run: ghp-import -n -p -f _build/html -c ${{ secrets.DOMAIN_DOT_NET }}

  post:
    name: Post
    if: ${{ github.event.pull_request.merged == true }}
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.24
        with:
          channel-id: ${{ secrets.CHANNEL_ID }}
          slack-message: "GitHub build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

  release-please:
    name: Release
    needs: post
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          package-name: jb-notes
